@startuml
'https://plantuml.com/class-diagram

class User {
    -id: UUID
    -firstName: String
    -lastName: String
    -email: Email
    -password: String
}

class Role {
    -id: Long
    -name: String
}

class Permission {
    -id: Long
    -name: String
}

User -> Role: -roles: Collection<Role>

Role --> Permission: -permissions: Collection<Permission>

@enduml